#!/bin/bash
#
#  WHAT IS THIS:
# 
#  - This script simply invokes mutt to send an email with all files found in the GRAPHS_FOLDER. THis is where we've stored the graphs generated by RRDTOOL in the previous step.
#
#  - The script uses a pre-configured Gmail account to send the message to my personal email
#
#  SCRIPT DEPENDENCIES: mutt    <- Install package before running this script
#
#  SCRIPT VARIABLES:
HOSTNAME="<hostname>"
GRAPHS_FOLDER="/home/user/elrond-monitor/GRAPHS"
EMAIL="<my_email_address>"

echo "Last Login on this server: `last | sed -n 1p`" | mutt -s "Elrond Monitor Report for $HOSTNAME `date +\"%d-%m-%Y\"`" -a $GRAPHS_FOLDER/* -- $EMAIL